import json

import requests
from langgraph.graph import END, StateGraph

from rule_automation.model_setup import get_llm
from rule_automation.prompt_template import format_user_rule


FASTAPI_URL = "http://127.0.0.1:5001/rules"


class State(dict):
    """Holds conversation state including user input and API responses."""

    user_input: str
    rule_json: dict
    create_approved: bool
    start_approved: bool
    result: dict


def llm_node(state: State) -> State:
    llm = get_llm()
    user_input = state["user_input"]
    formatted_messages = format_user_rule(user_input)
    response = llm.invoke(formatted_messages)

    try:
        rule_json = json.loads(response.content)
    except json.JSONDecodeError:
        raise ValueError("LLM returned invalid JSON")

    state["rule_json"] = rule_json
    return state


def hitl_createrule_node(state: State) -> State:
    """Simulates human-in-the-loop approval for rule creation ."""
    rule_json = state["rule_json"]
    print("AI: Human review required for rule generated by LLM :")
    print(json.dumps(rule_json, indent=2))

    user_approval = input("AI: Do you approve this rule? (yes/no): ").strip().lower()

    if user_approval == "yes":
        state["create_approved"] = True
    else:
        state["create_approved"] = False
        print("\nAI: Rule was rejected. Skipping API call for creating rule.")
        state["result"] = {
            "message": "Rule rejected by human."
        }
    return state


def create_rule_node(state: State) -> State:
    """Calls backend API to create the rule if approved."""
    create_resp = requests.post(f"{FASTAPI_URL}/create", json=state["rule_json"]).json()
    rule_id = create_resp.get("rule_id")
    print(f"\nAI: Rule created successfully with ID: {rule_id}")
    state["result"] = {
        "rule_id": rule_id,
        "message": create_resp.get("message")
    }
    return state


def hitl_startrule_node(state: State) -> State:
    """Simulates human-in-the-loop approval for rule starting ."""
    rule_id = state["result"]["rule_id"]
    print(f"AI: Human approval required for starting rule with ID: {rule_id}:")

    user_approval = input(
        f"AI: Do you want me to start this rule with ID: {rule_id} for you? (yes/no): "
    ).strip().lower()

    if user_approval == "yes":
        state["start_approved"] = True
    else:
        state["start_approved"] = False
        print(
            f"\nAI: Rule starting for rule ID: {rule_id} was disallowed. "
            "Skipping API call to start rule."
        )
        state["result"] = {
            "message": (
                f"Rule with ID:{rule_id} has been created but rule start "
                "has been disallowed by human."
            )
        }
        return state

    return state


def start_rule_node(state: State) -> State:
    """Calls backend API to start the rule if approved."""
    rule_id = state["result"]["rule_id"]

    start_resp = requests.post(f"{FASTAPI_URL}/{rule_id}/start").json()
    state["result"] = {
        "rule_id": rule_id,
        "message": start_resp.get("message")
    }
    return state


def build_graph():
    graph = StateGraph(State)

    graph.add_node("llm_node", llm_node)
    graph.add_node("hitl_createrule_node", hitl_createrule_node)
    graph.add_node("create_rule_node", create_rule_node)
    graph.add_node("hitl_startrule_node", hitl_startrule_node)
    graph.add_node("start_rule_node", start_rule_node)

    graph.set_entry_point("llm_node")
    graph.add_edge("llm_node", "hitl_createrule_node")
    graph.add_conditional_edges(
        "hitl_createrule_node",
        lambda state: "create_rule_node" if state.get("create_approved") else END,
        {"create_rule_node": "create_rule_node", END: END}
    )

    graph.add_edge("create_rule_node", "hitl_startrule_node")
    graph.add_conditional_edges(
        "hitl_startrule_node",
        lambda state: "start_rule_node" if state.get("start_approved") else END,
        {"start_rule_node": "start_rule_node", END: END}
    )
    graph.add_edge("start_rule_node", END)

    return graph.compile()
